protocol_mapping:
  RRBS: rrbs
  WGBS: wgbs
  EG: wgbs

pipelines:
  wgbs:
    name: WGBS  # Name used by pypiper so looper can find the logs
    path: src/wgbs.py
    looper_args: True
    required_input_files: [data_source]
    ngs_input_files: [data_source]
    arguments:
      "--sample-name": sample_name
      "--genome": genome
      "--input": data_source
      "--single-or-paired": read_type
    resources:
      default:
        file_size: "0"
        cores: "4"
        mem: "4000"
        time: "0-02:00:00"
      small:
        file_size: "0.3"
        cores: "8"
        mem: "32000"
        time: "2-00:00:00"        
      medium:
        file_size: "3"
        cores: "16"
        mem: "64000"
        time: "4-00:00:00"
      high:
        file_size: "10"
        cores: "24"
        mem: "64000"
        time: "7-00:00:00"
      huge:
        file_size: "30"
        cores: "16"
        mem: "128000"
        time: "4-00:00:00"
        partition: "largemem"

  rrbs:
    name: RRBS
    path: src/rrbs.py
    looper_args: True
    required_input_files: [data_source]
    all_input_files: [data_source, read1, read2]
    ngs_input_files: [data_source, read1, read2]
    arguments:
      "--sample-name": sample_name
      "--genome": genome
      "--input": data_source
      "--single-or-paired": read_type
    optional_arguments:
      "--input2": read2
      "--dark-bases": dark_bases
    resources:
      default:
        file_size: "0"
        cores: "4"
        mem: "4000"
        time: "0-02:00:00"      
      small:
        file_size: "0.3"
        cores: "4"
        mem: "16000"
        time: "1-00:00:00"
      medium:
        file_size: "2"
        cores: "4"
        mem: "24000"
        time: "1-12:00:00"
      high:
        file_size: "4"
        cores: "6"
        mem: "24000"
        time: "2-00:00:00"
