# This project config file describes your project. See looper docs for details.

metadata:  # relative paths are relative to this config file
  sample_annotation: microtest_annotation.csv  # sheet listing all samples in the project
  output_dir: $HOME/atac_out  # ABSOLUTE PATH to the parent, shared space where project results go
  pipelines_dir: "../pipeline_interface.yaml"  # ABSOLUTE PATH the directory where looper will find the pipeline repository
  
# in your sample_annotation, columns with these names will be populated as described 
# in the data_sources section below
derived_columns: [read1, read2]  

data_sources:  # This section describes paths to your data
  # specify the ABSOLUTE PATH of input files using variable path expressions
  # These keys then correspond to values in your sample annotation columns.
  # Variables specified using brackets are populated from sample_annotation columns. 
  test_data_R1: "examples/test_data/{sample_name}_R1.fastq.gz"
  test_data_R2: "examples/test_data/{sample_name}_R2.fastq.gz"
  microtest: "$CODEBASE/microtest/data/{filename}"

implied_columns:
  organism:
    human:
      genome: hg38
    mouse:
      genome: mm10
  