# This project config file describes your project. See looper docs for details.

sample_table: microtest_annotation.csv  # sheet listing all samples in the project

looper:
  output_dir: $HOME/dnameth  # ABSOLUTE PATH to the parent, shared space where project results go
  pipelines_dir: "../pipeline_interface.yaml"  # ABSOLUTE PATH the directory where looper will find the pipeline repository
  
# in your sample_annotation, columns with these names will be populated as described 
# in the data_sources section below
sample_modifiers:
  imply:
  - if:
      organism: human
    then:
      genome: hg38
  - if:
      organism: mouse
    then:
      genome: mm10
  derive:
    attributes: [read1, read2]  
    sources:  # This section describes paths to your data
      test_data_R1: "examples/test_data/{sample_name}_R1.fastq.gz"
      test_data_R2: "examples/test_data/{sample_name}_R2.fastq.gz"
      microtest: "$CODEBASE/microtest/data/{filename}"
      
